services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: app_app
    ports:
      - "9988:8080"
      - "9222:9222"  # Expose remote debugging port
    depends_on:
      - nats
      - mysql
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=linkedin_db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - LINKEDIN_EMAIL=${LINKEDIN_EMAIL}
      - LINKEDIN_PASSWORD=${LINKEDIN_PASSWORD}
      - NATS_URL=${NATS_URL}
    volumes:
      - /dev/shm:/dev/shm
    stop_signal: SIGINT

  nats:
    image: nats:latest
    ports:
      - "4222:4222"

  mysql:
    image: mysql:9.0
    env_file:
      - .env
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: linkedin
      PMA_PASSWORD: linkedin
      PMA_ARBITRARY: 1
    ports:
      - "9987:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
