services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: app_app
    ports:
      - "9988:8080"
    depends_on:
      - nats
      - mysql
    env_file:
      - .env
    stop_signal: SIGINT

  nats:
    image: nats:latest
    ports:
      - "4222:4222"

  mysql:
    image: mysql:9.0
    env_file:
      - .env
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
