name: Build and Test Flask App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m unittest discover tests
      
    - name: Build Docker image
      run: |
        docker build -t linkedin-crawler .
    
    - name: Run Docker container
      run: |
        docker run -d -p 5000:5000 linkedin-crawler
        
    - name: Check if application is running
      run: |
        sleep 10  # Give the application some time to start
        curl http://localhost:5000 || exit 1
